Shader "Custom/ConeStepMapping"
{
    Properties
    {
        [MainColor] _BaseColor("Base Color", Color) = (1, 1, 1, 1)
        [MainTexture] _BaseMap("Base Map", 2D) = "white" {}

        // Height in R channel of the (arbitrary) source heightmap. Not stored in the
        // anisotropic cone map, so we sample it separately.
        _HeightMap("Height Map", 2D) = "white" {}
        [Enum(Red,0,Green,1,Blue,2,Alpha,3)] _HeightChannel("Height Channel", Float) = 0

        // RGBA = (+X, -X, +Y, -Y) cone tangent ratios, generated by
        // RobustConeMapGenerator with _Anisotropic = 1. Must be sampled bilinearly -
        // the 3x3-min BilinearSafetyPass is what makes that safe.
        _ConeMap("Cone Map (Anisotropic)", 2D) = "white" {}

        _ParallaxScale("World Depth Range", Float) = 1.0
        _OrthoSize("Texture World Size", Float) = 2.0
        _ParallaxOffset("Parallax Offset", Float) = 0.0

        _MinError("Min Error", Float) = 0.001
        _MaxIterations("Max Primary Iterations", Float) = 64
        _MaxBinaryIterations("Max Binary Search Iterations", Float) = 16

        // Step relaxation multiplier. Keep <= 1 for Conservative mode
        //      Relaxed mode tolerates > 1 since overshoot is caught by the binary search refine.
        _Relax("Relax", Float) = 1.0

        // 0 = Conservative cone map: never penetrates, plain convergence loop.
        // 1 = Relaxed/corrected cone map: guaranteed at most one penetration,
        //     so we march until we penetrate (or run out of iterations), then
        //     binary-search back to the surface.
        [Toggle] _UseRelaxedCone("Use Relaxed Cone Map", Float) = 0

        [Toggle] _UseHistory("Use History (reprojection hook, off by default)", Float) = 0
        [Toggle] _UseTestTexture("Use Test Texture", Float) = 0
    }

    SubShader
    {
        Tags { "RenderType" = "Opaque" "RenderPipeline" = "UniversalPipeline" }

        Pass
        {
            Name "ConeStepMappingMRT"
            Tags { "LightMode" = "ConeStepMRT" }
            Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha

            HLSLPROGRAM

            #pragma vertex vert
            #pragma fragment frag

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

            // --- Structs ---

            struct Attributes
            {
                float4 positionOS : POSITION;
                float2 uv : TEXCOORD0;
                float3 normalOS : NORMAL;
                float4 tangentOS : TANGENT;
            };

            struct Varyings
            {
                float4 positionHCS : SV_POSITION;
                float2 uv : TEXCOORD0;
                float3 tangentViewDir : TEXCOORD1;
                float4 screenPos : TEXCOORD2;
                float4 prevScreenPos : TEXCOORD3;
                float3 positionWS : TEXCOORD4;
                float3 normalWS : TEXCOORD5;
                float3 tangentWS : TEXCOORD6;
                float3 bitangentWS : TEXCOORD7;
            };

            struct FragmentOutput
            {
                half4 color0 : SV_Target0;
                half4 color1 : SV_Target1;
                float depth : SV_Depth;
            };

            // Result of a cone-step march. "t" mirrors the old shader's "depth" field:
            // fraction of full penetration along the ray (0 = surface entry, 1 = deepest).
            struct ConeStepResult
            {
                float2 uv;
                float t;
                float error;
                bool wasHit;
                bool penetrated; // relaxed mode only, diagnostic
            };

            // --- Textures & Samplers ---

            TEXTURE2D(_BaseMap);
            SAMPLER(sampler_BaseMap);

            TEXTURE2D(_HeightMap);
            SAMPLER(sampler_HeightMap);

            TEXTURE2D(_ConeMap);
            SAMPLER(sampler_ConeMap);
            float4 _ConeMap_TexelSize; // auto-filled by Unity: x=1/width, y=1/height

            TEXTURE2D(_PreviousFrame);
            SAMPLER(sampler_PreviousFrame);

            // --- Constant Buffers ---

            CBUFFER_START(UnityPerMaterial)
                half4 _BaseColor;
                float4 _BaseMap_ST;
                float _HeightChannel;
                float _ParallaxScale, _OrthoSize, _ParallaxOffset;
                float _MinError;
                float _MaxIterations;
                float _MaxBinaryIterations;
                float _Relax;
                float _UseRelaxedCone, _UseHistory, _UseTestTexture;
            CBUFFER_END

            // Declared outside the per-material CBUFFER to stay SRP-batcher compatible,
            // matching how _CustomPrevViewProjMatrix is set up in the existing MRT shader.
            float4x4 _CustomPrevViewProjMatrix;

            // --- Helper Functions ---

            float3 ComputeTangentViewDir(Attributes IN)
            {
                float3 binormalOS = cross(IN.normalOS, IN.tangentOS.xyz) * IN.tangentOS.w;
                float3x3 objectToTangent = float3x3(IN.tangentOS.xyz, binormalOS, IN.normalOS);

                float3 cameraPosOS = TransformWorldToObject(_WorldSpaceCameraPos.xyz);
                float3 viewDirOS = cameraPosOS - IN.positionOS.xyz;

                return mul(objectToTangent, viewDirOS);
            }

            float4 ComputePrevScreenPos(Attributes IN)
            {
                float4 worldPos = mul(UNITY_MATRIX_M, float4(IN.positionOS.xyz, 1.0));
                float4 prevClipPos = mul(_CustomPrevViewProjMatrix, worldPos);
                return ComputeScreenPos(prevClipPos);
            }

            float4 GetHeightChannelMask()
            {
                if (_HeightChannel < 0.5) return float4(1, 0, 0, 0);
                if (_HeightChannel < 1.5) return float4(0, 1, 0, 0);
                if (_HeightChannel < 2.5) return float4(0, 0, 1, 0);
                return float4(0, 0, 0, 1);
            }

            float SampleHeight(float2 uv, float4 heightMask)
            {
                float4 c = SAMPLE_TEXTURE2D_LOD(_HeightMap, sampler_HeightMap, uv, 0);
                return dot(c, heightMask);
            }

            // Picks the one channel of the quad-directional cone map that bounds the
            // current ray direction. Since the ray direction is fixed for the whole
            // march, this only needs to be computed once per pixel, outside the loop.
            // R = +X, G = -X, B = +Y, A = -Y (matches RobustConeMapGenerator.compute).
            float4 GetConeChannelMask(float2 rayDirXY)
            {
                bool xDominant = abs(rayDirXY.x) >= abs(rayDirXY.y);
                if (xDominant)
                    return rayDirXY.x > 0 ? float4(1, 0, 0, 0) : float4(0, 1, 0, 0);
                else
                    return rayDirXY.y > 0 ? float4(0, 0, 1, 0) : float4(0, 0, 0, 1);
            }

            float SampleConeRatio(float2 uv, float4 coneChannelMask)
            {
                float4 c = SAMPLE_TEXTURE2D_LOD(_ConeMap, sampler_ConeMap, uv, 0);
                return dot(c, coneChannelMask);
            }

            // Advances sc by one cone step and returns the new value.
            // ds: normalized 3D ray direction, ds.xy horizontal (UV), ds.z vertical (height).
            // dominantAxis: max(|ds.x|, |ds.y|) - the anisotropic analogue of length(ds.xy).
            // remaining: vertical gap between the ray and the sampled surface height at
            //            the CURRENT sc (positive while still above the surface).
            // minStep: floor to guarantee forward progress against near-vertical cones.
            float NextConeStep(float sc, float remaining, float coneRatio, float3 ds, float dominantAxis, float relax, float minStep)
            {
                float denom = max(coneRatio * ds.z + dominantAxis, 1e-6);
                float step = remaining * coneRatio / denom;
                return sc + relax * max(minStep, step);
            }

            // --- Conservative cone stepping ---
            // The conservative map guarantees the cone never touches the surface except
            // at its own apex, so a plain step-and-converge loop can never overshoot
            // through the surface.
            ConeStepResult MarchConservative(float2 u0, float3 ds, float dominantAxis, float4 coneChannelMask, float4 heightMask, float startSc, float minStep)
            {
                ConeStepResult result;
                float sc = startSc;
                float error = 1.0;
                int iterations = (int)_MaxIterations;
                int i = 0;

                [loop]
                for (i = 0; i < iterations; i++)
                {
                    float2 p = u0 + ds.xy * sc;
                    float height = SampleHeight(p, heightMask);
                    error = 1.0 - ds.z * sc - height;
                    if (error <= _MinError) break;

                    float coneRatio = SampleConeRatio(p, coneChannelMask);
                    sc = NextConeStep(sc, error, coneRatio, ds, dominantAxis, _Relax, minStep);
                }

                result.uv = u0 + ds.xy * sc;
                result.t = ds.z * sc;
                result.error = error;
                result.wasHit = i < iterations;
                result.penetrated = false;
                return result;
            }

            // --- Relaxed cone stepping ---
            // The relaxed/corrected map only guarantees AT MOST ONE penetration, so we
            // march forward (allowed to overshoot into the surface once), then binary
            // search back between the last safe sc and the first penetrating sc.
            ConeStepResult MarchRelaxed(float2 u0, float3 ds, float dominantAxis, float4 coneChannelMask, float4 heightMask, float startSc, float minStep)
            {
                ConeStepResult result;
                float sc = startSc;
                float scPrev = startSc;
                float error = 1.0;
                float errorPrev = 1.0;
                bool penetrated = false;
                int iterations = (int)_MaxIterations;
                int i = 0;

                [loop]
                for (i = 0; i < iterations; i++)
                {
                    float2 p = u0 + ds.xy * sc;
                    float height = SampleHeight(p, heightMask);
                    error = 1.0 - ds.z * sc - height;

                    if (error <= 0.0)
                    {
                        penetrated = true;
                        break;
                    }
                    if (error <= _MinError) break;

                    float coneRatio = SampleConeRatio(p, coneChannelMask);
                    scPrev = sc;
                    errorPrev = error;
                    sc = NextConeStep(sc, error, coneRatio, ds, dominantAxis, _Relax, minStep);
                }

                if (penetrated)
                {
                    float lo = scPrev, hi = sc;
                    float hiErr = error;
                    int binaryIterations = (int)_MaxBinaryIterations;

                    [loop]
                    for (int j = 0; j < binaryIterations; j++)
                    {
                        float mid = 0.5 * (lo + hi);
                        float2 pm = u0 + ds.xy * mid;
                        float hMid = SampleHeight(pm, heightMask);
                        float errMid = 1.0 - ds.z * mid - hMid;

                        if (abs(errMid) <= _MinError)
                        {
                            lo = hi = mid;
                            hiErr = errMid;
                            break;
                        }

                        if (errMid > 0.0) { lo = mid; }
                        else { hi = mid; hiErr = errMid; }
                    }

                    sc = hi;   // land on/just past the surface rather than back above it
                    error = hiErr;
                }

                result.uv = u0 + ds.xy * sc;
                result.t = ds.z * sc;
                result.error = error;
                result.wasHit = penetrated || (i < iterations);
                result.penetrated = penetrated;
                return result;
            }

            // --- Reprojection hook ---
            // Not enabled by default (_UseHistory = 0). When enabled, reprojects the
            // previous frame's converged UV onto THIS frame's ray direction to get a
            // candidate starting sc, and compares its error against a fresh sc = 0
            // start, keeping whichever is closer to the surface. This mirrors
            // IterativeParallax.shader's GetStartUV, adapted to sc-space.
            //
            // What is intentionally NOT implemented here (left for you to add):
            // disocclusion/rejection heuristics, confidence-based blending, and
            // history validity beyond the screen-space bounds check below.
            float GetStartSc(float4 historyData, float2 prevScreenUV, float2 u0, float3 ds, float4 heightMask)
            {
                bool isHistoryValid = _UseHistory > 0.5 &&
                                       prevScreenUV.x >= 0.0 && prevScreenUV.x <= 1.0 &&
                                       prevScreenUV.y >= 0.0 && prevScreenUV.y <= 1.0 &&
                                       historyData.w > 0.5;

                if (!isHistoryValid) return 0.0;

                // Project the historical UV back onto this frame's ray direction to
                // recover an equivalent sc. ds.xy is not unit length in UV terms alone
                // (it's part of the normalized 3D ray), so divide out its own length.
                float2 historyUV = historyData.xy;
                float denom = max(dot(ds.xy, ds.xy), 1e-8);
                float scHistory = max(0.0, dot(historyUV - u0, ds.xy) / denom);

                float2 pFresh = u0;
                float2 pHistory = u0 + ds.xy * scHistory;

                float errorFresh = 1.0 - SampleHeight(pFresh, heightMask);
                float errorHistory = 1.0 - ds.z * scHistory - SampleHeight(pHistory, heightMask);

                // Only take the history start if it's still above the surface (positive
                // error) and better than starting fresh - otherwise fall back to sc = 0.
                if (errorHistory > 0.0 && errorHistory < errorFresh) return scHistory;
                return 0.0;
            }

            // --- Vertex Shader ---

            Varyings vert(Attributes IN)
            {
                Varyings OUT;
                VertexPositionInputs posInputs = GetVertexPositionInputs(IN.positionOS.xyz);
                OUT.positionHCS = TransformObjectToHClip(IN.positionOS.xyz);
                OUT.positionWS = posInputs.positionWS;
                OUT.uv = TRANSFORM_TEX(IN.uv, _BaseMap);
                OUT.tangentViewDir = ComputeTangentViewDir(IN);
                OUT.screenPos = ComputeScreenPos(OUT.positionHCS);
                OUT.prevScreenPos = ComputePrevScreenPos(IN);
                return OUT;
            }

            // --- Fragment Shader ---

            FragmentOutput frag(Varyings IN)
            {
                FragmentOutput output;

                float3 viewDir = normalize(IN.tangentViewDir);

                // Direction moved in UV space per unit height traversed across the
                // full [0,1] height range. Reuses _ParallaxScale/_OrthoSize the same
                // way the existing parallax shader does.
                float2 maxOffsetVector = (-viewDir.xy / viewDir.z) * (_ParallaxScale / _OrthoSize) + _ParallaxOffset;

                // Normalized 3D ray direction for the sc-parametrized march.
                // ds.xy: horizontal UV direction. ds.z: vertical (height) component.
                float3 ds = normalize(float3(maxOffsetVector, 1.0));
                float dominantAxis = max(abs(ds.x), abs(ds.y));
                float4 coneChannelMask = GetConeChannelMask(ds.xy);
                float4 heightMask = GetHeightChannelMask();
                float minStep = min(_ConeMap_TexelSize.x, _ConeMap_TexelSize.y);
                // float minStep = 1e-5;

                float2 prevScreenUV = IN.prevScreenPos.xy / IN.prevScreenPos.w;
                float4 historyData = SAMPLE_TEXTURE2D(_PreviousFrame, sampler_PreviousFrame, prevScreenUV);

                if (_UseTestTexture)
                {
                    output.color0 = SAMPLE_TEXTURE2D(_BaseMap, sampler_BaseMap, historyData.xy) * _BaseColor;
                    output.color1 = historyData;
                    output.depth = 0;
                    return output;
                }

                float startSc = GetStartSc(historyData, prevScreenUV, IN.uv, ds, heightMask);

                ConeStepResult result;
                if (_UseRelaxedCone > 0.5)
                {
                    result = MarchRelaxed(IN.uv, ds, dominantAxis, coneChannelMask, heightMask, startSc, minStep);
                }
                else
                {
                    result = MarchConservative(IN.uv, ds, dominantAxis, coneChannelMask, heightMask, startSc, minStep);
                }

                // Write our current state to MRT1 for the next frame.
                // R, G = current UV, B = last error, A = valid pixel flag.
                output.color1 = float4(result.uv, result.error, result.wasHit ? 1.0 : 0.0);
                output.depth = result.t > 0.999 ? 0 : result.t;

                bool outOfBounds = result.uv.x < 0.0 || result.uv.x > 1.0 ||
                                    result.uv.y < 0.0 || result.uv.y > 1.0;

                if (!result.wasHit || outOfBounds)
                {
                    discard;
                    output.color0 = float4(1, 0, 0, 1);
                    return output;
                }

                // 1. Ray direction in world space (from camera to quad surface)
                float3 viewDirWS = normalize(IN.positionWS - _WorldSpaceCameraPos.xyz);

                // 2. Distance traveled along the ray to reach the hit depth
                float rayDistance = (result.t * (_ParallaxScale / _OrthoSize)) / max(viewDir.z, 1e-5);

                // 3. True 3D hit location in World Space
                float3 hitPositionWS = IN.positionWS + viewDirWS * rayDistance;

                // 4. Transform hit point to Clip Space
                float4 hitHCS = TransformWorldToHClip(hitPositionWS);

                // 5. Output true hardware depth (handles Reversed-Z vs standard Z automatically)
                output.depth = hitHCS.z / hitHCS.w;

                // Output MRTs
                output.color1 = float4(result.uv, result.error, 1.0);
                half4 color = SAMPLE_TEXTURE2D(_BaseMap, sampler_BaseMap, result.uv) * _BaseColor;
                output.color0 = color;

                return output;
            }
            ENDHLSL
        }
    }
}
