Shader "Custom/ConeStepMapping"
{
    Properties
    {
        [MainColor] _BaseColor("Base Color", Color) = (1, 1, 1, 1)
        [MainTexture] _BaseMap("Base Map", 2D) = "white" {}

        // Height in R channel of the (arbitrary) source heightmap. Not stored in the
        // anisotropic cone map, so we sample it separately.
        _HeightMap("Height Map", 2D) = "white" {}
        [Enum(Red,0,Green,1,Blue,2,Alpha,3)] _HeightChannel("Height Channel", Float) = 0

        // RGBA = (+X, -X, +Y, -Y) cone tangent ratios, generated by
        // RobustConeMapGenerator with _Anisotropic = 1. Must be sampled bilinearly -
        // the 3x3-min BilinearSafetyPass is what makes that safe.
        _ConeMap("Cone Map (Anisotropic)", 2D) = "white" {}

        _ParallaxScale("World Depth Range", Float) = 1.0
        _OrthoSize("Texture World Size", Float) = 2.0
        _ParallaxOffset("Parallax Offset", Float) = 0.0

        _MinError("Min Error", Float) = 0.001
        _MaxIterations("Max Primary Iterations", Float) = 64
        _MaxBinaryIterations("Max Binary Search Iterations", Float) = 16

        // Step relaxation multiplier. Keep <= 1 for Conservative mode
        //      Relaxed mode tolerates > 1 since overshoot is caught by the binary search refine.
        _Relax("Relax", Float) = 1.0

        // 0 = Conservative cone map: never penetrates, plain convergence loop.
        // 1 = Relaxed/corrected cone map: guaranteed at most one penetration,
        //     so we march until we penetrate (or run out of iterations), then
        //     binary-search back to the surface.
        [Toggle] _UseRelaxedCone("Use Relaxed Cone Map", Float) = 0

        [Toggle] _UseHistory("Use History (reprojection hook, off by default)", Float) = 0
        _ReprojectionMarginWeight("Reprojection Margin Weight", Float) = 1.0
        _ReprojectionProgressWeight("Reprojection Progress Weight", Float) = 1.0
        [Toggle] _UseTestTexture("Use Test Texture", Float) = 0
    }

    SubShader
    {
        Tags { "RenderType" = "Opaque" "RenderPipeline" = "UniversalPipeline" }

        Pass
        {
            Name "ConeStepMappingMRT"
            Tags { "LightMode" = "ConeStepMRT" }
            Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
            // Integer targets cannot blend. Target 2 is only attached by the
            // renderer feature's step-count debug toggle.
            Blend 2 Off

            HLSLPROGRAM

            #pragma vertex vert
            #pragma fragment frag

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

            // Structs, textures/samplers, cbuffer, and basic sampling helpers.
            #include "Includes/ConeStepMappingCommon.cginc"
            // Conservative / relaxed marching loops.
            #include "Includes/ConeStepMarch.cginc"
            // History reprojection hook (isolated - expected to grow).
            #include "Includes/ConeStepReprojection.cginc"

            // --- Vertex Shader ---

            Varyings vert(Attributes IN)
            {
                Varyings OUT;
                VertexPositionInputs posInputs = GetVertexPositionInputs(IN.positionOS.xyz);
                OUT.positionHCS = TransformObjectToHClip(IN.positionOS.xyz);
                OUT.positionWS = posInputs.positionWS;
                OUT.uv = TRANSFORM_TEX(IN.uv, _BaseMap);
                OUT.tangentViewDir = ComputeTangentViewDir(IN);
                OUT.screenPos = ComputeScreenPos(OUT.positionHCS);
                OUT.prevScreenPos = ComputePrevScreenPos(IN);
                return OUT;
            }

            // --- Fragment Shader ---

            FragmentOutput frag(Varyings IN)
            {
                FragmentOutput output;
                output.stepCount = 0;

                float3 viewDir = normalize(IN.tangentViewDir);

                // Direction moved in UV space per unit height traversed across the
                // full [0,1] height range. Reuses _ParallaxScale/_OrthoSize the same
                // way the existing parallax shader does.
                float2 maxOffsetVector = (-viewDir.xy / viewDir.z) * (_ParallaxScale / _OrthoSize) + _ParallaxOffset;

                // Normalized 3D ray direction for the sc-parametrized march.
                // ds.xy: horizontal UV direction. ds.z: vertical (height) component.
                float3 ds = normalize(float3(maxOffsetVector, 1.0));
                float dominantAxis = max(abs(ds.x), abs(ds.y));
                float4 coneChannelMask = GetConeChannelMask(ds.xy);
                float4 heightMask = GetHeightChannelMask();
                float minStep = min(_ConeMap_TexelSize.x, _ConeMap_TexelSize.y);
                // float minStep = 1e-5;

                float2 prevScreenUV = IN.prevScreenPos.xy / IN.prevScreenPos.w;
                float4 historyData = SAMPLE_TEXTURE2D(_PreviousFrame, sampler_PreviousFrame, prevScreenUV);

                if (_UseTestTexture)
                {
                    output.color0 = SAMPLE_TEXTURE2D(_BaseMap, sampler_BaseMap, historyData.xy) * _BaseColor;
                    output.color1 = historyData;
                    output.depth = 0;
                    return output;
                }

                float startSc = GetStartSc(historyData, prevScreenUV, IN.uv, ds, heightMask);

                // Duplicate the validity check from GetStartSc so we can pass it to the loop
                bool isHistoryValid = _UseHistory > 0.5 && _UseRelaxedCone <= 0.5 &&
                                      prevScreenUV.x >= 0.0 && prevScreenUV.x <= 1.0 &&
                                      prevScreenUV.y >= 0.0 && prevScreenUV.y <= 1.0 &&
                                      historyData.w > 0.5;

                ConeStepResult result;
                if (_UseRelaxedCone > 0.5)
                {
                    result = MarchRelaxed(IN.uv, ds, dominantAxis, coneChannelMask, heightMask, startSc, minStep);
                }
                else
                {
                    result = MarchConservative(IN.uv, ds, dominantAxis, coneChannelMask, heightMask, startSc, minStep, historyData, isHistoryValid);
                }

                output.stepCount = result.steps;

                // Write our current state to MRT1 for the next frame.
                // R, G = best reprojection apex UV, B = its height, A = valid.
                // This is intentionally independent of result.uv, which remains
                // the actual converged surface hit used for shading and depth.
                output.color1 = float4(result.seedUV, result.seedHeight, result.seedValid ? 1.0 : 0.0);
                output.depth = result.t > 0.999 ? 0 : result.t;

                bool outOfBounds = result.uv.x < 0.0 || result.uv.x > 1.0 ||
                                    result.uv.y < 0.0 || result.uv.y > 1.0;

                if (!result.wasHit || outOfBounds)
                {
                    discard;
                    output.color0 = float4(1, 0, 0, 1);
                    return output;
                }

                // 1. Ray direction in world space (from camera to quad surface)
                float3 viewDirWS = normalize(IN.positionWS - _WorldSpaceCameraPos.xyz);

                // 2. Distance traveled along the ray to reach the hit depth
                float rayDistance = (result.t * (_ParallaxScale / _OrthoSize)) / max(viewDir.z, 1e-5);

                // 3. True 3D hit location in World Space
                float3 hitPositionWS = IN.positionWS + viewDirWS * rayDistance;

                // 4. Transform hit point to Clip Space
                float4 hitHCS = TransformWorldToHClip(hitPositionWS);

                // 5. Output true hardware depth (handles Reversed-Z vs standard Z automatically)
                output.depth = hitHCS.z / hitHCS.w;

                // Output MRTs
                output.color1 = float4(result.seedUV, result.seedHeight, result.seedValid ? 1.0 : 0.0);
                half4 color = SAMPLE_TEXTURE2D(_BaseMap, sampler_BaseMap, result.uv) * _BaseColor;
                output.color0 = color;

                return output;
            }
            ENDHLSL
        }
    }
}
